# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af4642f5a82161fda9e47d13e8039d14e831cf3a59fe73f5a1a4ee103509a374fba72a20b3da7ec56f16d7e155f56d8d23d4959ecff5da1f23e555d1f3950a01

test:
  secret_key_base: 497c0d80f0215bad4a410b19ff065610bb280a13a1c3ebf23ae22e50574b2c716d9a2368d92a2eef35bb74fdc27fa64911dbf181b7113030f60f124d9643000c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
